version: '3'

services:

  web:

    # restart rules for the container - setting restart to 'always' keeps restarting the container even if it errors out1
    restart: unless-stopped

    # telling docker-compose where our dockerfile for this service is
    build: 
      context: ./backend
      dockerfile: Dockerfile

    image: nodejs
    container_name: nodejs

    ports:
      - 8000:8000

    volumes:
      - ./backend:/code

    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB


    command: ["npm", "start"]
